  - name: Create DNS entry
    ovh_dns: state=present domain={{ tld_hostname }} name=drive type=CNAME value={{ admin_vm_name }}.{{ tld_hostname }}.
    tags: dns

  - name: Add Nextcloud Nginx conf file
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/nextcloud.conf mode=0440
    notify:
     - Reload Nginx

  - name: Nextcloud - MariaDB
    docker_containe:
      name: "{{ nextcloud.db.host }}"
      image: mariadb
      restart_policy: always
      volumes:
        - /data/nextcloud/mysql:/var/lib/mysql
      env:
        MYSQL_DATABASE: "{{ nextcloud.db.name }}"
        MYSQL_USER: "{{ nextcloud.db.user }}"
        MYSQL_PASSWORD: "{{ nextcloud.db.pass }}"
        MYSQL_ROOT_PASSWORD: "{{ nextcloud.db.root_pass }}"
      networks: 
        - name: "{{ env }}-net"

  - file: path=/data/nextcloud/mysql/dumps state=directory mode=770
  - file: path=/data/nextcloud/etc owner=nobody group=nogroup state=directory mode=770
  - file: path=/data/nextcloud/data owner=nobody group=nogroup state=directory mode=770

  - name: Nextcloud - Redis
    docker_container:
      name: nextcloud-redis
      image: redis:latest
      restart_policy: always
      volumes:
        - /data/nextcloud/redis:/var/lib/redis
      networks: 
        - name: "{{ env }}-net"

  - name: Nextcloud
    docker_container:
      networks:
        - name: "{{ env }}-net"
      name: nextcloud
      image: "{{ nextcloud.docker_image }}"
      env:
        UID: 65534
        GID: 65534
        UPLOAD_MAX_SIZE: 10G
        APC_SHM_SIZE: 128M
        OPCACHE_MEM_SIZE: 128
        CRON_PERIOD: 15m
        TZ: Europe/Paris
        DOMAIN: "drive.{{ tld_hostname }}"
        DB_TYPE: mysql
        DB_NAME: "{{ nextcloud.db.user }}"
        DB_USER: "{{ nextcloud.db.user }}"
        DB_PASSWORD: "{{ nextcloud.db.pass }}"
        DB_HOST: "{{ nextcloud.db.host }}"
      volumes:
        - /data/nextcloud/data:/data
        - /data/nextcloud/etc:/config
        - /data/nextcloud/apps:/apps2
        - /data/nextcloud/themes:/nextcloud/themes

  - name: Wait forr DB to start
    pause: seconds=20

  - name: Create monitoring user in MariaDB
    command: docker exec {{ nextcloud.db.host }} mysql -p{{ nextcloud.db.root_pass }} -e "CREATE USER '{{ monitoring.db.user }}'@'%' IDENTIFIED BY '{{ monitoring.db.pass }}';"
    ignore_errors: yes
  - name: Create roles for moonitoring processes in MariaDB
    command: docker exec {{ nextcloud.db.host }} mysql -p{{ nextcloud.db.root_pass }} -e "GRANT PROCESS ON *.* TO '{{ monitoring.db.user }}'@'%';"
  - name: Create roles for monitoring perfs in MariaDB
    command: docker exec {{ nextcloud.db.host }} mysql -p{{ nextcloud.db.root_pass }} -e "GRANT SELECT ON performance_schema.* TO '{{ monitoring.db.user }}'@'%';"

  - name: Setup DB
    command: docker exec -t -u nobody nextcloud sh -c 'cd /usr/share/nginx/html/nextcloud && php -f /usr/local/bin/occ  maintenance:install --database=mysql --database-name={{ nextcloud['db']['name'] }} --database-host={{ nextcloud['db']['host'] }} --database-table-prefix={{ nextcloud['db']['table_prefix'] }} --data-dir=/usr/share/nginx/html/nextcloud/data  --database-user={{ nextcloud['db']['user'] }} --database-pass={{ nextcloud['db']['pass'] }} --admin-user={{ nextcloud['admin']['user'] }} --admin-pass="{{ nextcloud['admin']['pass'] }}"'
    ignore_errors: yes

  - name: Setup LDAP auth
    command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ app:enable user_ldap
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:create-empty-config
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapHost ldap
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapPort 389
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapBase {{ ldap['top_dn'] }}
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapAgentName {{ ldap['bind_dn'] }}
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapAgentPassword {{ ldap['pass'] }}
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapBaseGroups {{ ldap['base_groups_dn'] }}
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapBaseUsers {{ ldap['base_users_dn'] }}
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapCacheTTL 600
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupDisplayName cn
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupFilter (&(|(objectclass=groupOfNames)(objectclass=posixGroup))(|(cn=admin)(cn=administrators)(cn=admins)(cn=developpers)(cn=users)))
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupFilterGroups admin;administrators;admins;developpers;users
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupFilterMode 0
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupFilterObjectclass groupOfNames;posixGroup
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapGroupMemberAssocAttr member
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapLoginFilter (&(|(objectclass=inetOrgPerson)(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(mail=%uid)(uid=%uid))))
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapLoginFilterAttributes mail;uid
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapLoginFilterEmail 1
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapLoginFilterMode 0
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapLoginFilterUsername 1
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapNestedGroups 0
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapPagingSize 500
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapTLS 0
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUserDisplayName cn
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUserFilter (|(objectclass=inetOrgPerson)(objectclass=posixAccount))
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUserFilterMode 1
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUserFilterObjectclass inetOrgPerson;posixAccount
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUuidGroupAttribute auto
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUuidUserAttribute auto
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapOffCertCheck 0
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" useMemberOfToDetectMembership 1
    ignore_errors: yes
  - command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapConfigurationActive 1
    ignore_errors: yes
  #- command: docker exec -t -u nobody nextcloud php -f /usr/local/bin/occ ldap:set-config "" ldapUserFilterGroups
  #  ignore_errors: yes

  - name: Setup hostname
    command: sed -i -e "s/0 => 'localhost',/0 => 'localhost',1 => 'drive.{{ tld_hostname }}',/" /data/nextcloud/etc/config.php

  - name: Setup Redis cache
    command: sed -i -e "s/);/'memcache.local' => '\\\\OC\\\\Memcache\\\\Redis', 'memcache.distributed' => '\\\\OC\\\\Memcache\\\\Redis', 'memcache.locking' => '\\\\OC\\\\Memcache\\\\Redis', 'redis' => array('host' => 'nextcloud-redis', 'port' => 6379, ), );/" /data/nextcloud/etc/config.php

  - name: Create backup folder
    file: path={{ backup.path }}/{{ env }}/nextcloud-data state=directory mode=700

  - name: Cron backup Nextcloud DB
    cron: 
      name: Cron backup Nextcloud DB
      minute: "0"
      hour: "3"
      job: dogwrap -n "Cron backup Nextcloud DB" -k {{ datadog.api_key }} --submit_mode errors  "docker exec {{ nextcloud.db.host }} mysqldump --all-databases -u root -p{{ nextcloud.db.root_pass }} | gzip > {{ backup.path }}/{{ env }}/nextcloud-dump-$(date +%Y%m%d%H%M).gz" 2>&1
    when: backup

  - name: Cron backup Nextcloud data
    cron: 
      name: Cron backup Nextcloud data
      minute: "0"
      hour: "3"
      job: dogwrap -n "Cron backup Nextcloud data" -k {{ datadog.api_key }} --submit_mode errors  "rsync -azs /data/nextcloud/data {{ backup.path }}/{{ env }}/nextcloud-data" 2>&1
    when: backup

  - name: Cron Nextcloud background jobs
    cron: 
      name: Cron Nextcloud background jobs
      minute: "*/15"
      job: dogwrap -n "Cron Nextcloud background jobs" -k {{ datadog.api_key }} --submit_mode errors  "curl -k https://nextcloud.{{ tld_hostname }}/cron.php" 2>&1

  - name: Restart Nginx
    command: docker restart nginx
